import {createApi,fetchBaseQuery} from '@reduxjs/toolkit/query/react'


export const userApi = createApi({
  reducerPath: 'userApi',
  baseQuery: fetchBaseQuery({ 
    baseUrl: 'http://localhost:3001/api/v1' ,
    prepareHeaders: (headers, { getState }) => {
      //Type de contenu
      headers.set('Content-Type', 'application/json');
      headers.set('Access-Control-Allow-Headers','Accept');

      // Récupérer le token depuis le store Redux
      const token = getState().auth?.token;

        if (token){
          headers.set('Authorization', `Bearer ${token}`);
        }
        return headers;
      }
    },
  ),
  endpoints: (builder) => ({
    getUser : builder.mutation({
      query : () => ({
        url: '/user/profile',
        method: 'POST',
      }),
    })
  })
});




// export const userApi = createApi({
//   reducerPath: 'userApi',
//   baseQuery: fetchBaseQuery({ 
//     baseUrl: 'http://localhost:3001/api/v1' ,
//     prepareHeaders: (headers, { getState }) => {
//       //Type de contenu
//       headers.set('Accept', 'application/json');
//       headers.set('Access-Control-Allow-Headers','Accept');

//       // Récupérer le token depuis le store Redux
//       const token = useSelector(state => state.auth?.token);
  
//         if (token){
//           headers.set('Authorization', `Bearer ${token}`);
//         }
  
//         console.log(headers)
//         return headers;
//     }
//     },
//   ),
//   endpoints: (builder) => ({
//     getUser : builder.mutation({
//       query : () => ({
//         url: '/user/profile',
//         method: 'POST',
//       }),
//       hook : 'useGetUserMutation'
//     }),
//     updateUser : builder.mutation({
//       query : (user) => ({
//         url: '/user/profile',
//         method: 'PUT',
//         body: user
//       }),
//       hook : 'useUpdateUserMutation'
//     }),
//   })
// });


// Hooks are auto-generated by RTK-Query
export const { useGetUserMutation } = userApi;